/**
 * AI Message Types and Configuration Interfaces
 * 
 * Standardized message format for all AI provider communications.
 * This ensures consistency across Ollama, OpenAI, Gemini, and DeepSeek.
 */

/**
 * Message roles in a conversation.
 * Based on the standard chat completion format used by most LLM APIs.
 */
export enum AIMessageRole {
  /** System-level instructions that guide the model's behavior */
  SYSTEM = 'system',
  /** Messages from the end user */
  USER = 'user',
  /** Messages generated by the AI assistant */
  ASSISTANT = 'assistant',
}

/**
 * A single message in a conversation.
 */
export interface AIMessage {
  /** The role of the message sender */
  role: AIMessageRole;
  /** The content of the message */
  content: string;
}

/**
 * Configuration options for AI provider requests.
 * Supports all common parameters plus provider-specific extensions.
 */
export interface AIProviderConfig {
  /** The model identifier to use (e.g., 'gpt-4', 'gemini-pro', 'deepseek-chat') */
  model: string;
  
  /** Maximum number of tokens to generate */
  maxTokens?: number;
  
  /** Sampling temperature (0.0 to 2.0). Higher = more random/creative */
  temperature?: number;
  
  /** System prompt to set the model's behavior and context */
  systemPrompt?: string;
  
  /** 
   * Additional provider-specific configuration.
   * Allows extensibility for provider-specific features.
   * 
   * Examples:
   * - top_p: number (nucleus sampling)
   * - top_k: number (top-k sampling)
   * - presence_penalty: number
   * - frequency_penalty: number
   * - stop_sequences: string[]
   */
  [key: string]: unknown;
}

/**
 * Standard response format from AI providers.
 * Unifies different provider response formats into a single interface.
 */
export interface AIResponse {
  /** The generated text content */
  content: string;
  
  /** 
   * Total tokens used (prompt + completion).
   * Note: Some providers don't return token counts, in which case this is estimated.
   */
  tokensUsed: number;
  
  /** The model that generated the response */
  model: string;
  
  /** The provider identifier (e.g., 'ollama', 'openai', 'gemini', 'deepseek') */
  provider: string;
}

/**
 * A chunk of a streaming response.
 * Used in async iterables for real-time response delivery.
 */
export interface AIStreamChunk {
  /** The text content of this chunk */
  content: string;
  
  /** 
   * Whether this is the final chunk of the stream.
   * When true, no more chunks will follow.
   */
  done: boolean;
  
  /**
   * Token count information (may be available on the final chunk).
   * Not all providers return this during streaming.
   */
  tokensUsed?: number;
  
  /** The model generating the response */
  model: string;
  
  /** The provider identifier */
  provider: string;
}

/**
 * Information about an AI model.
 * Used for model selection and discovery.
 */
export interface AIModelInfo {
  /** The model identifier (e.g., 'gpt-4', 'gemini-2.0-flash-exp') */
  name: string;
  
  /** Human-readable display name (e.g., 'GPT-4') */
  displayName?: string;
  
  /** The provider that offers this model */
  provider: string;
  
  /** Maximum tokens this model supports */
  maxTokens?: number;
  
  /** Whether the model is currently available for use */
  isAvailable?: boolean;
  
  /**
   * Additional model metadata.
   * Provider-specific features and capabilities.
   */
  metadata?: {
    /** Whether the model supports streaming */
    supportsStreaming?: boolean;
    /** Whether the model supports vision/multimodal inputs */
    supportsVision?: boolean;
    /** Whether the model supports function calling */
    supportsFunctions?: boolean;
    /** Context window size in tokens */
    contextWindow?: number;
    /** Model description */
    description?: string;
    /** Additional provider-specific properties */
    [key: string]: unknown;
  };
}

/**
 * Helper function to convert a single prompt string to messages array.
 * Useful for providers that accept both formats.
 */
export function promptToMessages(
  prompt: string,
  systemPrompt?: string,
): AIMessage[] {
  const messages: AIMessage[] = [];
  
  if (systemPrompt) {
    messages.push({
      role: AIMessageRole.SYSTEM,
      content: systemPrompt,
    });
  }
  
  messages.push({
    role: AIMessageRole.USER,
    content: prompt,
  });
  
  return messages;
}

/**
 * Helper function to estimate tokens from text length.
 * Uses the standard approximation of ~4 characters per token.
 */
export function estimateTokensFromText(text: string): number {
  if (!text || text.length === 0) return 0;
  return Math.ceil(text.length / 4);
}
